### ISSUE TITLE
`TypeUuid` incompatibility in bevy_easings with bevy

### ISSUE THREAD

**Issue by jamadazi** [mockersf/bevy_extra#3]
Using the latest git commit of both bevy_extras and bevy:

```
error[E0405]: cannot find trait `TypeUuid` in crate `bevy::type_registry`
   --> /home/jamadazi/src/bevy_extra/bevy_easings/src/plugin.rs:194:66
    |
194 | fn handle_ease_system<T: Ease + Component + bevy::type_registry::TypeUuid>(
    |                                                                  ^^^^^^^^ not found in `bevy::type_registry`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0405`.
error: could not compile `bevy_easings`
```

**Comment by mockersf** [comment]
Code work on latest git commit of bevy, but dependency is still to 0.2.1...

You should override the bevy dependency with
```
[patch.crates-io]
bevy = { git = "https://github.com/bevyengine/bevy" }
```

If you cloned the repo locally, I think patching doesn't work and you'll have to update the dependency in your cloned repo.

Hopefully 0.3.0 of bevy should be released soon!

**Comment by jamadazi** [comment]
Now that bevy 0.3 has been released, can you confirm that the crate is ready to go out of the box (dependencies set correctly, etc.) and close this issue?

**Comment by mockersf** [comment]
new versions just published 👍
